// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfskQ0MK1lnI2boRq___9MiRykbGYj9p4',
    appId: '1:507123618012:android:f9ac50c684b2c73bdf6419',
    messagingSenderId: '507123618012',
    projectId: 'l-ikun',
    databaseURL: 'https://l-ikun-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'l-ikun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIVGEypwp_jt3gVBy_AUdKF4dyK7S2ndg',
    appId: '1:507123618012:ios:f9902894e2d7f6f6df6419',
    messagingSenderId: '507123618012',
    projectId: 'l-ikun',
    databaseURL: 'https://l-ikun-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'l-ikun.appspot.com',
    iosClientId: '507123618012-sh4j01u7b1h12kutqkm4egdph2arri6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
